baseURL = "https://stefklein.github.io" # The URL of your site
languageCode = "en-gb" # The language you want to display the site in
title = "Stefan Kis" # The title you want to appear in the address bar
theme = "hugo-developer-portfolio" # The theme, don't change this


[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"
# navigation
[menu]
  [[menu.main]]
  name = "About"
  URL = "about"
  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Personal website of Stefan Kis."
author = "Stefan Kis"

[params.contact]
  enable = true
  formAction = "https://formspree.io/f/mwkynnbn" # Add your formspree URL here to get emails

  # This contains the contact information for the footer
[params.footer]
  email = "stefklein.at@gmail.com"
  address = "Innsbruck, AT"
